services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    init: true
    environment:
      NODE_ENV: development
      PORT: 3000
      KV_REST_API_URL: redis://redis:6379
      KV_REST_API_TOKEN: mock
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
volumes:
  redis_data: